export const teamMembers = [
  { id: 1, name: "Aarjummm Adhikari", role: "Sr. Officer-Marketing & Education", linkedin: "", email: "aarju.adhikari@gargdental.com", status: true },
  { id: 2, name: "Anil Kumar Shah", role: "Sr. Officer-Sales & Marketing", linkedin: "", email: "anil.shah@gargdental.com", status: true },
  { id: 3, name: "Balkrishna Shrestha", role: "Deputy Manager-", linkedin: "", email: "balkrishna.shrestha@gargdental.com", status: true },
  { id: 4, name: "Bikash Tamang", role: "Officer - Sales", linkedin: "", email: "bikash@gargdental.com", status: false },
  { id: 5, name: "Dipendra Thapa", role: "Marketing Executive", linkedin: "", email: "dipendra@gargdental.com", status: true },
  { id: 6, name: "Hari Bahadur", role: "Support Staff", linkedin: "", email: "hari@gargdental.com", status: true },
  { id: 7, name: "Santosh Kuikel", role: "Sr. Manager - Sales & Support", linkedin: "", email: "santosh.kuikel@gargdental.com", status: true },
  { id: 8, name: "Shital Gautam", role: "Coordinator-Sales & Marketing", linkedin: "https://linkedin.com/in/shital", email: "shital.gautam@gargdental.com", status: true },
  { id: 9, name: "Sunil Kumar Pandit Chhetri", role: "Sr. Officer-Sales & Marketing", linkedin: "", email: "sunil.pandit@gargdental.com", status: true },
  { id: 10, name: "Tika Hang Limbu", role: "Manager-Marketing", linkedin: "", email: "tika.limbu@gargdental.com", status: true },
  { id: 11, name: "Tika Hang Limbu", role: "Manager-Marketing", linkedin: "", email: "tika.limbu@gargdental.com", status: true },
  { id: 12, name: "Tika Hang Limbu", role: "Manager-Marketing", linkedin: "", email: "tika.limbu@gargdental.com", status: true },
  { id: 13, name: "Tika Hang Limbu", role: "Manager-Marketing", linkedin: "", email: "tika.limbu@gargdental.com", status: true },
  { id: 14, name: "Tika Hang Limbu", role: "Manager-Marketing", linkedin: "", email: "tika.limbu@gargdental.com", status: true },
  { id: 15, name: "Tika Hang Limbu", role: "Manager-Marketing", linkedin: "", email: "tika.limbu@gargdental.com", status: true },
  { id: 16, name: "Tika Hang Limbu", role: "Manager-Marketing", linkedin: "", email: "tika.limbu@gargdental.com", status: true },
  { id: 17, name: "Tikajjj Hang Limbu", role: "Manager-Marketing", linkedin: "", email: "tika.limbu@gargdental.com", status: true },
];
